# -*- coding: utf-8 -*-
# Copyright: 2018-present Samsung Electronics Co., Ltd. and other contributors

version: "2"

networks:
  castanets-net:
  
services:
  default:
    build: .
    command: --version

  browser:
    build: .
    command: --no-sandbox https://github.com/samsung/castanets
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    networks:
      castanets-net:
        aliases:
         - castanets-host.castanets-net

  renderer:
    build: .
    command: --no-sandbox --type=renderer --server-address=castanets_host
    networks:
      - castanets-net

  nfsbrowser:
    build: .
    command: --no-sandbox https://github.com/samsung/castanets --shared-memory-nfs-path=/tmp/castanets.tmp
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix
    environment:
      - DISPLAY=${DISPLAY}
    networks:
      castanets-net:
        aliases:
         - castanets-host.castanets-net

  nfsrenderer:
    build: .
    command: --no-sandbox --type=renderer --server-address=castanets-host --shared-memory-nfs-path=/tmp/castanets.tmp  
    networks:
      - castanets-net
